### PR TITLE
Add vendor model pages

### PR DESCRIPTION
**Pull request by Jaibles**
@shakeelanjum why did you have to pull the scripts from footer.php and put them into each individual file? Having the scripts neatly in one php helps to avoid the issue of having *inconsistencies across files.

I can see that you are loading the scripts in the head of your files instead and you obviously have a reason so if you can explain it in your pull requests so I know what your doing and why?

*If it's the case that they have to be moved, I presume we also have to do it for /uses (and sub-pages)

### CODE REVIEW

**Comment by Jaibles** [comment]
@shakeelanjum did you put the scripts in `uses, uses/construction, etc.`also, if not I'll add them.

**Comment by shakeelanjum** [comment]
@Jaibles: having script tags in .php takes longer to load required javascript code (e.g. jquery, custom, etc.). And subsequent javascript code runs before or in-parallel-to the other scripts are loaded on page. Hence erroring as jQuery is not defined OR $ is not defined etc. That's why taken out the javascript includes outside of serverside code.

**Comment by Jaibles** [comment]
ok thanks Shaqeel, it should be done for /uses pages also then yea?

**Comment by Jaibles** [comment]
:+1:

**Pull request merged**
